on: [push]

jobs:
  jack-of-all-trades:
    name: Build, Test and Artifact
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Install Dependencies
      run: npm install
    - name: Build
      run: npm build
    - name: Test
      run: npm test
    - name: Deploy to Firebase
      uses: w9jds/firebase-action@master
      with:
        args: deploy --only hosting
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}