on: [push]

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Install Dependencies
      run: npm install
    - name: Build
      run: npm build
    - name: Test
      run: npm test
    - name: Archive Production Artifact
      uses: actions/upload-artifact@master
      with:
        name: public
        path: public
  deploy:
    name: Deploy
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Download Artifact
        uses: actions/download-artifact@master
        with:
          name: public
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}