on: [push]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    - uses: actions/checkout@master
    - run: npm install
    - run: npm test
  build:
    name: Build
    needs: test
    runs-on: ubuntu-latest
    - uses: actions/checkout@master
    - run: npm install
    - run: npm build
    - uses: actions/upload-artifact@master
      with:
        name: app
        path: public
  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
      - uses: actions/checkout@master
      - uses: actions/download-artifact@master
        with:
          name: app
      - uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
